# ======================================================================
# GitHub Pages Default Configuration
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
# ======================================================================

# Site variables
title: My Bicycles
author: John Neffenger

# Sass/SCSS
sass:
  style: :compressed

# GitHub Pages
safe: true
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
